### PR TITLE
Update RuntimeConfig.cs

### PR DESCRIPTION
**Pull request by sallywuzhere**
Fixed a null-reference exception during the removal of preloaded assets

### CODE REVIEW

**Comment by stephen-systemfriend** [comment]
I came here to make this exact same pull request. Is there anything stopping this being merged into the internal branch?

**Comment by macekj** [comment]
As of making this comment this issue is still present and this is the only fix I was able to found. Would be really helpful to get this fix merged in.

**Comment by devbridie** [comment]
Thanks for bumping this up; this is most likely going to make it in to the next release.

**Review by miguelleon88 — APPROVED** [review]

**Comment by devbridie** [comment]
This went out here: https://github.com/google-ar/arcore-unity-extensions/commit/c47d03c3b9a06adf8a0699fd7eca50e6532ac7c6#diff-74f9a4b22141f4faca575d692d29b34156430a10abf84148979ab9c21e96bf53L79

**Pull request closed without merging**
