### PR TITLE
Fix native collection memory leak in ARCoreAnalytics

### LINKED ISSUE #79: A Native Collection has not been disposed
I am encountering a bug where native collections are not being disposed of. I am using the version ARCore Extensions for AR Foundation v1.32.0.

```
A Native Collection has not been disposed, resulting in a memory leak. Allocated from:
Unity.Collections.NativeArray`1:.ctor(Byte[], Allocator) (at /Users/bokken/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:69)
UnityEngine.Networking.UploadHandlerRaw:.ctor(Byte[]) (at /Users/bokken/buildslave/unity/build/Modules/UnityWebRequest/Public/UploadHandler/UploadHandler.bindings.cs:95)
Google.XR.ARCoreExtensions.Editor.Internal.ARCoreAnalytics:SendAnalytics(String, LogRequest) (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@abb3767358/Editor/Scripts/Internal/ARCoreAnalytics.cs:105)
Google.XR.ARCoreExtensions.Editor.Internal.ARCoreAnalytics:.cctor() (at Library/PackageCache/com.google.ar.core.arfoundation.extensions@abb3767358/Editor/Scripts/Internal/ARCoreAnalytics.cs:55)
```

### PR DESCRIPTION
**Pull request by mtschoen-unity**
Fixes #79 

Turns out this one is pretty simple. I encountered this issue in Unity 2021.3.0f1, and after making this change I'm not seeing the error anymore. I think the `UploadHandlerRaw` class started using native collections somewhere along the way and now needs to be explicitly disposed. I will work on updating our docs to make this more clear.

I considered a null check on the upload handler (`_webRequest.uploadHandler?.Dispose`) in case there's some edge case where it's null but I don't think that's necessary.

### CODE REVIEW

**Review by devbridie — COMMENTED** [review]
How about [`_webRequest.Dispose();`](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.Dispose.html)? It seems like it would clean up the uploadhandler as well.

**Comment by mtschoen-unity** [comment]
> How about [_webRequest.Dispose();](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.Dispose.html)? It seems like it would clean up the uploadhandler as well.

Yep! That works too :)
I've pushed the change.

**Comment by voropserg** [comment]
Getting the same error on the 2021.3.7 regulary. 
It can sometimes interuprt the build process, so it would be nice for it to get fixed

**Comment by devbridie** [comment]
This has landed and will be fixed in the upcoming version of ARCore. Keeping this open for visibility until that release. Thanks for the contribution!

**Pull request closed without merging**
